### ISSUE TITLE
WinDivert Error

### ISSUE THREAD

**Issue by rafikahmed** [bitbrute/evillimiter-windows#1]
Hi, 
When I execute evillimiter on windows 10 and then choose the interface it shows me WinDivert Error handle could not be opened.
Any fix to this issue ?
Kind regards,
Ahmed.

**Comment by bitbrute** [comment]
Hey, thanks for reporting!
I was able to reproduce the error and realized that I failed to ship a required kernel driver.
The recent release should resolve the issue.

Would love to hear back from you!
~bitbrute

**Comment by rafikahmed** [comment]
Hi Bitbrute, 
I've tested it and now it works. Good Job !
Kind regards,
Ahmed.
