### ISSUE TITLE
Migrate to .NET Core

### ISSUE THREAD

**Issue by Korayem** [bitbrute/evillimiter-windows#10]
If that project can be migrated to .net core, it can be used to build a crossplatform app to support win, mac and linux

**Comment by bitbrute** [comment]
Unfortunately, [EvilLimiter for Windows](https://github.com/bitbrute/evillimiter-windows) requires a 3rd party library called [WinDivert](https://www.reqrypt.org/windivert.html) that is only available for Windows and absolutely crucial for the tool to work.
