### ISSUE TITLE
🔺 run it and no gui or tray of the software is appears 🔺

### ISSUE THREAD

**Issue by salimnachit** [bitbrute/evillimiter-windows#15]
Hi ,
i installed the software following all the instructions , but after pressing on the software i run it as admin and after that nothing happend ,not showing any GUI or tray .
Hope you read this and answer me with the fix of the problem . thanks 
i have Windows 10 1903 x64
.NET 2.0,3.5,4.8
------------------------------------
and what is that , a virus :  Trojan:Win32/Occamy.AA 
detected by Windows Defender

**Comment by bitbrute** [comment]
The software is quite buggy and I discontinued working on it.
Read [this](#7) issue to understand the trojan warnings.
