### ISSUE TITLE
Limiter acts like it's blocking the connection entirely.

### ISSUE THREAD

**Issue by rafikahmed** [bitbrute/evillimiter-windows#2]
Hi there, 
So I tested the limiter functionality, when I try to limit the Upload/Download speed for a host on my network it acts like it's blocking it from accessing the network not just limiting the speed.
Kind regards,
Ahmed.

**Comment by bitbrute** [comment]
Hey!

You didn't - by accident - limit/block the gateway too?
Did you set the limit to a reasonable amount (e.g. 60bit/s would obviously be too low)?
Is IP routing enabled in the "Settings" tab?
Are you connected to a repeater or using DLAN?

If the error still persists try setting the value of ```IpEnableRouter``` in the registry (```HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters```) to ```1``` and restart your machine.

Thank you!

**Comment by rafikahmed** [comment]
Hi There, 
Changing `IpEnableRouter ` fixed the issue.
Thank you!
Ahmed.

**Comment by bitbrute** [comment]
Update:
It seems like the IP routing service wasn't able to start properly. The issue should now be fixed.
By downloading the recent version, this error will no longer occur.

Thank you for reporting!
